#!/bin/bash

### BEGIN INIT INFO
# Provides:          device gateway
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: device gateway daemon incorporating Kinect v2, Continua Alliance devices and Arduino sensing
### END INIT INFO

DIR=/home/rem/wp3project/DeviceGateway
DESC="DGw clients service"
DAEMON=$DIR/run_dclients.sh
DAEMON_NAME="dgw-clients-daemon"

# Add any command line options for your daemon here
DAEMON_OPTS=""

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=root

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting service $DAEMON_NAME"
    start-stop-daemon --start -d $DIR --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping service $DAEMON_NAME"
    start-stop-daemon -d $DIR --stop --pidfile $PIDFILE --retry 10 --signal TERM
    log_end_msg $?
}
do_restart() {
    do_stop
    do_start
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0

#!/bin/sh
